"""
Django settings for myshop project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()  # 从 .env 文件加载环境变量

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-61(o-97i)9a&i(^azz+uys)x0+0o#68xkq8z5qynd^me(0gv%q'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CSRF_TRUSTED_ORIGINS = ['https://*.pythonanywhere.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shop',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myshop.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myshop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 1. 告诉 Django：用户上传的文件，请保存在项目根目录下的 'media' 文件夹里
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 2. 告诉浏览器：如果访问 'http://.../media/xxx.jpg'，就是想看图片
MEDIA_URL = '/media/'


# 登录成功后，默认跳转回首页
LOGIN_REDIRECT_URL = '/'
# 注销后跳转回首页
LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = 'login'

# === 真实的邮件发送配置 (QQ邮箱) ===

# 1. 指定使用 SMTP 后端 (不再是 Console)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# 2. 邮件服务器地址 (QQ是 smtp.qq.com, Gmail是 smtp.gmail.com, 网易是 smtp.163.com)
EMAIL_HOST = 'smtp.qq.com'

# 3. 端口号 (通常 SSL 使用 465)
EMAIL_PORT = 465

# 4. 你的邮箱账号/授权码
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'fallback@example.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', 'fallback_password')

# 5. 使用 SSL 加密链接 (必须为 True)
EMAIL_USE_SSL = True

# 6. 默认发件人 (必须和 EMAIL_HOST_USER 保持一致，否则会被拦截)
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER