# Generated by Django 5.2.8 on 2025-12-02 12:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('view', '浏览'), ('buy', '购买')], max_length=10, verbose_name='行为类型')),
                ('description', models.CharField(max_length=255, verbose_name='行为描述')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户日志',
                'verbose_name_plural': '客户浏览/购买日志',
                'ordering': ['-timestamp'],
            },
        ),
    ]
