# Generated by Django 5.2.8 on 2025-12-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_shipping_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('shipped', '发货中'), ('confirmed', '已收货')], default='pending', max_length=20, verbose_name='订单状态'),
        ),
    ]
